default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: 127.0.0.1

development:
  adapter: postgresql
  encoding: unicode
  database: uspo_developer
  username: postgres
  password: qwerty

test:
  <<: *default
  database: db/test

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: hastinik_development_production
  username: hastinik_development
  password: <%= ENV['IMPALA_DATABASE_PASSWORD'] %> 